repos:
  # Standardni pre-commit hookovi
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # Python lint (ruff = brži od flake8/pylint)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]

  # Python formatter (black)
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  # JavaScript/TypeScript lint (eslint)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.36.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        args: ['--config', 'frontend/eslint.config.js']
        additional_dependencies:
          - 'eslint@9.35.0'
          - '@eslint/js@9.35.0'
          - '@typescript-eslint/parser@8.44.0'
          - '@typescript-eslint/eslint-plugin@8.44.0'
          - 'eslint-config-next@15.5.2'

  #Detect secrets (sprječava commit lozinki i ključeva)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
